### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rjriajul** [rjriajul/telegram-image-upload-bot#1]
Error: 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/s/bot/main.py", line 1, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
ImportError: cannot import name 'Filters' from 'telegram.ext' (/usr/local/lib/python3.10/dist-packages/telegram/ext/__init__.py)

**Comment by rjriajul** [comment]
Solved#
